data_path: ./ # path for saving data

key_frame_distance: 2.0  # key frame distance density

graph_optimizer_type: g2o # currently support g2o

use_gnss: true

use_loop_close: false

optimize_step_with_key_frame: 10000  # optimization frequency when no information available

optimize_step_with_loop: 100  # optimization with loop closure frequency

optimize_step_with_gnss: 950  # optimization with gnss info frequency

g2o_param:
  odom_edge_noise: [0.5, 0.5, 0.5, 0.001, 0.001, 0.001] # noise: x y z yaw roll pitch
  close_loop_noise: [2.0, 2.0, 2.0, 0.01, 0.01, 0.01] # noise: x y z yaw roll pitch
  gnss_noise: [2.0, 2.0, 2.0] # 噪声：x y z We do not use the gnss orientation currently
