data_path: ./  # path for saving the map data

registration_method: NDT  # point cloud registration method

key_frame_distance: 2.0  # density of key frames

local_frame_size: 20  # size of the sliding window

local_map_filter: voxel_filter  # point cloud filtering method

# Rviz display
display_filter: voxel_filter

frame_filter: voxel_filter


# Configuration for each method mentioned above
# Matching
NDT:
  res: 1.0
  step_size: 0.1
  trans_eps: 0.01
  max_iter: 30

# Filtering
voxel_filter:
  local_map:
    leaf_size: [0.6, 0.6, 0.6]
  frame:
    leaf_size: [1.3, 1.3, 1.3]
  display:
    leaf_size: [0.5, 0.5, 0.5]
